app = "plp-hackathon"
primary_region = "jnb"

[build]

[env]
  VITE_API_URL = "https://plp-hackathon.fly.dev"
  
[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024